package org.sample.dao;

import java.util.Date;

public class SampleDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.sample_id
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private Long sampleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.sample_name
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private String sampleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.code
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.place
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.date
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.status
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.sample_id
     *
     * @return the value of sample.sample_id
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public Long getSampleId() {
        return sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.sample_id
     *
     * @param sampleId the value for sample.sample_id
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setSampleId(Long sampleId) {
        this.sampleId = sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.sample_name
     *
     * @return the value of sample.sample_name
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public String getSampleName() {
        return sampleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.sample_name
     *
     * @param sampleName the value for sample.sample_name
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setSampleName(String sampleName) {
        this.sampleName = sampleName == null ? null : sampleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.code
     *
     * @return the value of sample.code
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.code
     *
     * @param code the value for sample.code
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.place
     *
     * @return the value of sample.place
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.place
     *
     * @param place the value for sample.place
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.date
     *
     * @return the value of sample.date
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.date
     *
     * @param date the value for sample.date
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.status
     *
     * @return the value of sample.status
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.status
     *
     * @param status the value for sample.status
     *
     * @mbggenerated Wed Dec 21 22:13:43 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}